name: Run e2e tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        db: ['mssql', 'mysql', 'postgres', 'maria', 'sqlite3']
        node-version: [ '12-alpine', '14-alpine', '15-alpine' ]
    env:
      CACHED_IMAGE: ghcr.io/${{ github.repository_owner }}/directus-e2e-test-cache:${{ matrix.node-version }}
    steps:
      - name: Translate image name to lowercase
        run: echo $CACHED_IMAGE | awk '{print "CACHED_IMAGE="tolower($0)}'  >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull cached directus image
        run: |
          docker pull $CACHED_IMAGE || true
          docker tag $CACHED_IMAGE directus-test-image || true
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: restore node_modules cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies & Build
        run: |
          npm install
          npm run build
      - name: Run tests
        env:
          TEST_NODE_VERSION: ${{ matrix.node-version }}
          TEST_DB: ${{ matrix.db }}
        run: npm run test:e2e
      - name: Push cached image
        # only push the new cache image on the main branch once per node version
        if: github.ref == 'refs/heads/main' && matrix.db == 'sqlite3'
        run: |
          docker tag directus-test-image $CACHED_IMAGE
          docker push $CACHED_IMAGE
